# SPDX-License-Identifier: BSD-2-Clause
# X-SPDX-Copyright-Text: (c) Copyright 2024 Advanced Micro Devices, Inc.

name: "perform_build"

on:
  workflow_call:
    inputs:
      onloadBranch:
        description: "Version of onload to be built against"
        default: "master"
        required: true
        type: string
      onloadRepo:
        description: "Onload repository to checkout"
        default: "Xilinx-CNS/onload"
        required: true
        type: string
      tcpdirectPrimaryBranch:
        description: "Version of tcpdirect to build"
        default: "master"
        required: true
        type: string
      tcpdirectSecondaryBranch:
        description: "Version of tcpdirect to build if the primary version is unavailable"
        default: "master"
        required: false
        type: string
      tcpdirectRepo:
        description: "Version of tcpdirect to build"
        default: "Xilinx-CNS/tcpdirect"
        required: true
        type: string
      packetDrillBranch:
        description: "Version of onload to be built against"
        default: "master"
        required: true
        type: string
      packetDrillRepo:
        description: "Version of onload to be built against"
        default: "Xilinx-CNS/packetdrill-tcpdirect"
        required: true
        type: string


jobs:
  perform_build_and_test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: tcpdirect primary checkout
        id: primary_tcpdirect_checkout
        uses: actions/checkout@v4
        continue-on-error: true
        with:
          repository: ${{ inputs.tcpdirectRepo }}
          path: tcpdirect
          ref: ${{ inputs.tcpdirectPrimaryBranch }}

      - name: tcpdirect secondary checkout
        uses: actions/checkout@v4
        if: ${{ ! cancelled() && steps.primary_tcpdirect_checkout.outcome == 'failure' }}
        with:
          repository: ${{ inputs.tcpdirectRepo }}
          path: tcpdirect
          ref: ${{ inputs.tcpdirectSecondaryBranch }}

      - name: onload checkout public tree-ish
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.onloadRepo }}
          path: onload
          ref: ${{ inputs.onloadBranch }}

      - name: packetdrill checkout
        uses: actions/checkout@v4
        continue-on-error: true
        with:
          repository: ${{ inputs.packetDrillRepo }}
          path: packetdrill-tcpdirect
          ref: ${{ inputs.packetDrillBranch }}

      - name: Install TCPDirect Deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential perl

      - name: build
        run: |
          cd $GITHUB_WORKSPACE/tcpdirect
          ONLOAD_TREE=$GITHUB_WORKSPACE/onload NDEBUG=1 make -j $(nproc)

      - name: shim
        run: |
          cd $GITHUB_WORKSPACE/tcpdirect
          ONLOAD_TREE=$GITHUB_WORKSPACE/onload NDEBUG=1 ZF_DEVEL=1 TEST_THREAD_NAME=zf make -j $(nproc) shim

      - name: tests
        run: |
          cd $GITHUB_WORKSPACE/tcpdirect
          ONLOAD_TREE=$GITHUB_WORKSPACE/onload UT_OUTPUT=$GITHUB_STEP_SUMMARY NDEBUG=1 ZF_DEVEL=1 TEST_THREAD_NAME=zf make -j $(nproc) -k test
